### ISSUE TITLE
Switch to multiloader setup

### ISSUE THREAD

**Issue by klikli-dev** [klikli-dev/modonomicon#127]
# About 
If time is available, modonomicon should be made multiloader compatible.
The initial step would be to split the forge version into a common and forge part, and in a second step port the forge part to fabric.

# Tasks 

- [x] abstract bookstatecapability
- [x] abstract bookunlockcapability
- [x] abstract config
- [x] AdvancementEvent for BookUnlockStateManager#onAdvancement
- [x] abstract networking
  - use message class in common
  - abstract packet handling? need to handle the context forge provides vs fabric, either just hand over player or figure out what we need from them
- [x] Publish fabric, forge and common to maven
- [x] Publish fabric and forge to cf
- [x] item textures not loaded! - check multiloader example
- [x] merge main modonomicon fixes
- [x] update license info for new files
- [x] fix: fabric has no multi layer gui, so we just should re-open the category if an entry is closed

# Tests 
- [x] Test getting unlock code for a freshly reset book, if empty string -> show message
- [x] test backwards compat by using it with occultism
- [x] test book models on fabric
- [x] Test server + client
- [x] Test commands
